### ISSUE TITLE
Problem with staring project

### ISSUE THREAD

**Issue by kovalwaffe** [ixkaito/bathe#13]
node v15.4.0
I have a problem with starting: npm run dev

Error: No files matching the pattern "$npm_package_config_css_src/**/*" were found.
    at D:\xampp\htdocs\wordpress\wp-content\themes\bathe\node_modules\stylelint\lib\standalone.js:208:12
    at processTicksAndRejections (node:internal/process/task_queues:93:5)npm ERR! code 1
npm ERR! path D:\xampp\htdocs\wordpress\wp-content\themes\bathe
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c stylelint $npm_package_config_css_src/**/* --fix

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\koval\AppData\Local\npm-cache\_logs\2020-12-12T14_36_46_630Z-debug.log
ERROR: "sass" exited with 1.
npm ERR! code 1
npm ERR! path D:\xampp\htdocs\wordpress\wp-content\themes\bathe
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c npm-run-all -p imagemin sass webpack -p browser watch

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\koval\AppData\Local\npm-cache\_logs\2020-12-12T14_36_46_954Z-debug.log

**Comment by akiya64** [comment]
Thanks for report!
This error is reproduced om my Windows 10 / node v14.15.2 / npm v6.14.9.

On Windows shell, `npm run ` can not expand variables written `$npm_package_config_css_src` in package.json.
It is necessary to write `%npm_package_config_css_src` for Windows shell, but `npm run` on Linux or OS X expand variable with `$`.
May be bathe needs some npm package for closs platform.
Example: https://github.com/akabekobeko/npm-cross-conf-env
Ref: https://akabeko.me/blog/2016/05/cross-conf-env-1-0-release/ written in japanese.

**Comment by akiya64** [comment]
I adjusted "scripts" in package.json for Windows shell.

```json
  "scripts": {
    "dev": "npm-run-all -p imagemin sass webpack -p browser watch",
    "browser": "browser-sync \"http://%npm_package_config_browsersync_proxy%\" -f \"**/*.php\" \"%npm_package_config_css_dist%\" \"%npm_package_config_js_output%\" \"%npm_package_config_image_dist%\" --port %npm_package_config_browsersync_port%",
    "build": "run-p imagemin sass webpack",
    "imagemin": "node imagemin \"%npm_package_config_image_src%/**/*\" %npm_package_config_image_dist%",
    "presass": "stylelint \"%npm_package_config_css_src%/**/*\" --fix",
    "sass": "sass %npm_package_config_css_src%:%npm_package_config_css_dist% --style=compressed",
    "postsass": "postcss %npm_package_config_css_dist%/*.css --use=autoprefixer --dir=%npm_package_config_css_dist% %npm_package_config_css_map%",
    "webpack": "webpack %npm_package_config_js_entry% -o %npm_package_config_js_output%",
    "watch:imagemin": "onchange \"%npm_package_config_image_src%/**/*\" -e \".DS_Store\" -- npm run imagemin",
    "watch:sass": "onchange \"%npm_package_config_css_src%/**/*\" -e \".DS_Store\" -- npm run sass",
    "watch:webpack": "npm run webpack -- --watch",
    "watch": "run-p watch:*"
  },
```

I run "npm run dev" normally.
Not a fundamental solution, because does not expand variables on OS X or Linux by this rewrite.

**Comment by kovalwaffe** [comment]
Thank you very much for your help :)

**Comment by ixkaito** [comment]
@kovalwaffe Thanks for reporting!
@akiya64 Thanks for supporting.

**Comment by ixkaito** [comment]
@kovalwaffe I released a new cross-platform version. Please re-generate or re-download this template. If you still have any problems with `npm run dev`, please let me know.
