### ISSUE TITLE
Package is not complete

### ISSUE THREAD

**Issue by Xiquad** [ixkaito/bathe#17]
Package json config section is missing dist key for js.

**Comment by ixkaito** [comment]
@Xiquad Thanks for reporting. The dist key for js is `output`. Are there any issues about this?

**Comment by ixkaito** [comment]
@Xiquad I found a typo of `$npm_package_config_js_output` which was `$npm_package_config_js_dist` and fixed it. Thank you so much!

https://github.com/ixkaito/bathe/commit/787b0a1f4616d17d2c5e19187d730ebbb721cae0

**Comment by Xiquad** [comment]
Great! Thanks :)
