### ISSUE TITLE
Pb with npm run dev

### ISSUE THREAD

**Issue by iroshiva** [ixkaito/bathe#20]
Hi,

I downloaded bathe folder, setted it in the themes folder of a basic wordpress install, followed the others instructions.
When i ran $ npm run dev, http://localhost:3000 doesn't respond.

What can be the issue ?

Thx

**Comment by bitmeisterei** [comment]
same here

**Comment by ixkaito** [comment]
What WordPress local development environment are you using? For example, [Local](https://localwp.com/), [wp-env](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-env/), etc.

You have to modify the `proxy` of browsersync in `package.json` for your environment. For example, `yourproject.local`. The default value of `proxy` is `localhost:8888`. This is the default url of wp-env.

**Comment by ixkaito** [comment]
@stefancroft I think the default port of MAMP is `8888`. Please first check to see if http://localhost:8888 is displaying your site. If you didn't change the port of MAMP, you don't have to change the browsersync proxy in the package.json.

**Comment by fabricepallaud** [comment]
Doesn't work either for me.

**Comment by ixkaito** [comment]
@fabricepallaud What WordPress local development environment are you using? For example, [MAMP](https://www.mamp.info/en/mamp/mac/), [Local](https://localwp.com/), [wp-env](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-env/), etc.

**Comment by fabricepallaud** [comment]
@ixkaito I use XAMPP on Windows.

**Comment by ixkaito** [comment]
@fabricepallaud The default port of XAMPP seems to be `80`, so you need to change the value of `config.browsersync.proxy` in `package.json` to `localhost:80` (or `localhost`).

**Comment by ixkaito** [comment]
I'm closing this issue because it has been inactive for 30 days.
