### ISSUE TITLE
Can you update sass and tailwind?

### ISSUE THREAD

**Issue by zkmark** [ixkaito/bathe#41]
Can you update sass and tailwind? , or some problem would occur

tailwind is on version 3.4.3, and sass is on version 1.75.0 currently

I would also recommend using dependabot to update the packages

https://docs.github.com/en/code-security/getting-started/dependabot-quickstart-guide

**Comment by ixkaito** [comment]
@zkmark Thank you! Updated Tailwind CSS and Sass.
